### PR TITLE
add new js-tricks section + add new article

### PR DESCRIPTION
**Pull request by aminelejmi**

### CODE REVIEW

**Comment by 3imed-jaberi** [comment]
Hi @aminelejmi, thank you for your first contribution ❤️ ...

Please move the file to this path `blogs/languages/javascript` and change the file name with the blog title or some short expressed not README.md ..

> ⚠️Note: you can remove the `init.txt` file inside `blogs/languages/javascript`.

**Review by 3imed-jaberi — CHANGES_REQUESTED** [review]
Hi @aminelejmi, thank you for your first contribution ❤️ ...

Please move the file to this path `blogs/languages/javascript` and change the file name with the blog title or some short expressed not README.md ..

> ⚠️Note: you can remove the `init.txt` file inside `blogs/languages/javascript`.

**Comment by aminelejmi** [comment]
@3imed-jaberi changes done :)

**Review by 3imed-jaberi — APPROVED** [review]
LGTM 🚀 ..

**Pull request merged**
