### PR TITLE
UPDATE: docker,pipeline,graphQl blogs on 2020-05-19  12:10:58

### PR DESCRIPTION
**Pull request by hatembentayeb**

### CODE REVIEW

**Review by 3imed-jaberi — COMMENTED** [review]
LGTM, but ken tnajem tikteb les blogs hedhom b type hedha ;

```
esm-blog.md
**esmik**: [blog title](link-to blog)
```

**Comment by hatembentayeb** [comment]
ya3ni kol blog 3andou l file .md mte3ou ?

**Comment by hatembentayeb** [comment]
Done !

**Review by 3imed-jaberi — APPROVED** [review]
Great ^^ 🚀 ..

**Pull request merged**
